# Generated by Django 3.1.7 on 2021-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='Unanswered', max_length=300),
        ),
    ]
